# docker-compose.yml
version: '3.1'
services:
  app:
    build: .
    depends_on:
      - postgres
    ports:
      - "3000:3000"

  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: "postgres"
    ports:
      - "5432:5432" 
    volumes:
      - data:/var/lib/postgresql/data 

volumes:
  data:
    driver: local
