# docker-compose.yml
version: '3.1'
services:
  app:
    build: .
    depends_on:
      - postgres
    ports:
      - '3000:3000'
    volumes:
      - .:/usr/src/app

  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: 'postgres'
      POSTGRES_DB: 'engsoft'
    ports:
      - '5432:5432'
    volumes:
      - data:/var/lib/postgresql/data

volumes:
  data:
    driver: local
